version: '3.7'

services: 
  detector-db:
    container_name: detector-db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: metal-detector
    networks:
      - detector-network
    volumes:
      - type: volume
        source: detector-db-volume
        target: /var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  butler-db:
    container_name: butler-db
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-release-butler
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  butler-app:
    container_name: butler-app
    image: metaldetector/metal-release-butler
    environment:
      DATASOURCE_URL: jdbc:postgresql://butler-db:5432/metal-release-butler
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: secret
    networks:
      - butler-network
    ports:
      - 8095:8095
    restart: always

volumes:
  detector-db-volume:
  butler-db-volume:

networks:
  detector-network:
  butler-network:
