version: '3.7'

services: 
  detector-db:
    container_name: detector-db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/detector_db_root_password
      MYSQL_DATABASE: metal-detector
    secrets:
      - detector_db_root_password
    networks:
      - detector-network
    volumes:
      - type: volume
        source: detector-db-volume
        target: /var/lib/mysql
    ports:
      - 3306:3306
    restart: always
     
  detector-phpmyadmin:
    container_name: detector-db-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
     PMA_ARBITRARY: 1
     PMA_HOST: detector-db
    networks:
      - detector-network
    volumes:
      - type: volume
        source: detector-phpmyadmin-volume
        target: /sessions
    ports:
     - 9000:80
    restart: always

  butler-db:
    container_name: butler-db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/butler_db_root_password
      MYSQL_DATABASE: metal-release-butler
    secrets:
      - butler_db_root_password
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/mysql
    ports:
      - 3307:3306
    restart: always

  butler-phpmyadmin:
    container_name: butler-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
     PMA_ARBITRARY: 1
     PMA_HOST: butler-db
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-phpmyadmin-volume
        target: /sessions
    ports:
     - 9001:80
    restart: always

  butler-app:
    container_name: butler-app
    image: metaldetector/metal-release-butler
    environment:
      DATASOURCE_URL: jdbc:mysql://butler-db:3306/metal-release-butler?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: ${BUTLER_DB_ROOT_PASSWORD}
    networks:
      - butler-network
    ports:
      - 8095:8095
    restart: always

volumes:
  detector-db-volume:
  detector-phpmyadmin-volume:
  butler-db-volume:
  butler-phpmyadmin-volume:

secrets:
  detector_db_root_password:
    file: .secrets/detector_db_root_password.txt
  butler_db_root_password:
    file: .secrets/butler_db_root_password.txt

networks:
  detector-network:
  butler-network: