version: '3.7'

services: 
  detector-db:
    container_name: detector-db
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-detector
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - detector-network
    volumes:
      - type: volume
        source: detector-db-volume
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure:3

  butler-db:
    container_name: butler-db
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-release-butler
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: on-failure:3

  butler-app:
    container_name: butler-app
    image: metaldetector/metal-release-butler
    environment:
      DATASOURCE_URL: jdbc:postgresql://butler-db:5432/metal-release-butler
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: secret
      JWT_SECRET: secret
      ROCKS_METALDETECTOR_AUTHENTICATION_ENABLED: 'false'
    networks:
      - butler-network
    ports:
      - 8095:8080
    restart: on-failure:3

volumes:
  detector-db-volume:
  butler-db-volume:

networks:
  detector-network:
  butler-network:
