application:
  host: https://metal-detector.rocks

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: true
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

management:
  endpoints:
    web:
      base-path: ${ACTUATOR_BASE_PATH}

metal-release-butler:
  host: http://butler-app:8080
