name: Build and deploy docker container image

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: [ubuntu-latest]
    steps:
      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use node.js 14.x to compile frontend
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm --prefix webapp/src/main/resources/static/ts/ install
          npm --prefix webapp/src/main/resources/static/ts/ run prod-build

      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: metaldetector/metal-detector
          tags: ${{ steps.version.outputs.version }},latest
          build_args: BUILD_DATE=${{ steps.version.outputs.version }},VCS_REF=${{ github.ref }}

      - name: Push image to Heroku Registry
        run: |
          docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          docker tag metaldetector/metal-detector registry.heroku.com/${{ secrets.HEROKU_PREVIEW_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_PREVIEW_APP_NAME }}/web

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Deploy docker image on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_PREVIEW_APP_NAME }} web
