name: Docker Image

on:
  push:
    branches: 
      - master

jobs:
  build-image:
    runs-on: [ubuntu-latest]
    steps:
      - name: Create version string
        id: version
        run: echo "::set-output name=version::$(date -u +'%Y%m%dT%H%M%S')"

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm --prefix webapp/src/main/resources/static/ts/ install
          npm --prefix webapp/src/main/resources/static/ts/ run prod-build

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Publish to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: metaldetector/metal-detector
          tags: ${{ steps.version.outputs.version }},latest
          build_args: BUILD_DATE=${{ steps.version.outputs.version }},VCS_REF=${{ github.ref }}

  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy on heroku
        run: |
          docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          docker tag metaldetector/metal-detector registry.heroku.com/${{ secrets.HEROKU_PREVIEW_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_PREVIEW_APP_NAME }}/web
